
import React from 'react';
import { CalculationData, Supplier, SupplierStatus, TransportItem, Currency, Language } from '../types';
import { Truck, Calendar, Package, AlertCircle, BarChart, Printer, CheckCircle2, UserCircle, Globe, Combine, Layers } from 'lucide-react';

interface Props {
  data: CalculationData;
  onUpdateSupplier: (supplierId: string, updates: Partial<Supplier>) => void;
}

export const LogisticsView: React.FC<Props> = ({ data, onUpdateSupplier }) => {
  // Filter only included suppliers
  const activeSuppliers = data.suppliers.filter(s => s.isIncluded !== false);

  // Aggregate data
  const totalWeight = activeSuppliers.reduce((sum, s) => {
    return sum + s.items.reduce((itemSum, i) => itemSum + (i.weight * i.quantity), 0);
  }, 0);

  const totalTrucks = data.transport.reduce((sum, t) => {
      // Exclude linked suppliers if ignored
      if (t.supplierId) {
          const s = data.suppliers.find(x => x.id === t.supplierId);
          if (s && s.isIncluded === false) return sum;
      }
      return sum + t.trucksCount;
  }, 0);
  
  const statusCounts = {
      [SupplierStatus.TO_ORDER]: activeSuppliers.filter(s => s.status === SupplierStatus.TO_ORDER).length,
      [SupplierStatus.ORDERED]: activeSuppliers.filter(s => s.status === SupplierStatus.ORDERED).length,
  };

  const getStatusColor = (status: SupplierStatus) => {
      switch(status) {
          case SupplierStatus.TO_ORDER: return 'bg-red-100 text-red-700 border-red-200';
          case SupplierStatus.ORDERED: return 'bg-green-100 text-green-700 border-green-200';
      }
  };

  // --- PDF Generation ---
  const generateOrderPDF = (supplier: Supplier) => {
    const printWindow = window.open('', '', 'width=800,height=600');
    if (!printWindow) return;

    // Calc total
    const subtotal = supplier.items.reduce((sum, item) => {
        const price = supplier.isOrm ? (item.unitPrice * 0.5) : item.unitPrice;
        return sum + (item.quantity * price);
    }, 0);
    const total = subtotal * (1 - supplier.discount / 100);

    const lang = supplier.language;
    const isPL = lang === Language.PL;

    const t = {
        title: isPL ? "ZAMÓWIENIE" : "PURCHASE ORDER",
        date: isPL ? "Data" : "Date",
        orderingParty: isPL ? "ZAMAWIAJĄCY" : "ORDERING PARTY",
        supplier: isPL ? "Dostawca" : "Supplier",
        offerNo: isPL ? "Numer Oferty" : "Offer No",
        offerDate: isPL ? "Data Oferty" : "Offer Date",
        deliveryDate: isPL ? "Termin Dostawy" : "Delivery Date",
        colNo: isPL ? "Lp." : "No.",
        colDesc: isPL ? "Nazwa / Opis" : "Description",
        colComp: isPL ? "Nr komponentu" : "Component No.",
        colQty: isPL ? "Ilość" : "Qty",
        colWeight: isPL ? "Waga (kg)" : "Weight (kg)",
        colPrice: isPL ? "Cena jedn." : "Unit Price",
        colVal: isPL ? "Wartość" : "Value",
        sumNet: isPL ? "Suma netto" : "Subtotal",
        discount: isPL ? "Rabat" : "Discount",
        total: isPL ? "DO ZAPŁATY" : "TOTAL",
        footer: isPL ? "Wygenerowano automatycznie w systemie ProCalc." : "Automatically generated by ProCalc system.",
        notes: isPL ? "Uwagi" : "Notes"
    };

    const notesHtml = supplier.notes ? `
        <div style="margin-top: 30px; padding: 15px; background-color: #fcfcfc; border: 1px solid #eee;">
            <div style="font-weight: bold; margin-bottom: 5px; font-size: 14px;">${t.notes}:</div>
            <div style="font-size: 13px; white-space: pre-wrap;">${supplier.notes}</div>
        </div>
    ` : '';

    const html = `
      <html>
        <head>
          <title>${t.title} - ${supplier.name}</title>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; }
            .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #FFCC00; padding-bottom: 20px; }
            .title { font-size: 24px; font-weight: bold; color: #000; }
            .meta { margin-bottom: 30px; }
            .meta-row { display: flex; margin-bottom: 10px; }
            .meta-label { width: 150px; font-weight: bold; color: #444; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
            th { text-align: left; background: #f8f9fa; padding: 12px; border-bottom: 2px solid #ddd; font-size: 14px; }
            td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
            .total-section { text-align: right; font-size: 18px; font-weight: bold; }
            .footer { margin-top: 50px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">${t.title}</div>
            <div>${new Date().toLocaleDateString()}</div>
          </div>
          <div class="meta">
            <div class="meta-row"><span class="meta-label">${t.supplier}:</span> ${supplier.name}</div>
            <div class="meta-row"><span class="meta-label">${t.offerNo}:</span> ${supplier.offerNumber || '-'}</div>
            <div class="meta-row"><span class="meta-label">${t.offerDate}:</span> ${supplier.offerDate || '-'}</div>
            <div class="meta-row"><span class="meta-label">${t.deliveryDate}:</span> ${supplier.deliveryDate === 'ASAP' ? 'ASAP' : (supplier.deliveryDate || '-')}</div>
          </div>
          <table>
            <thead>
              <tr>
                <th>${t.colNo}</th>
                <th>${t.colDesc}</th>
                <th>${t.colComp}</th>
                <th style="text-align:center">${t.colQty}</th>
                <th style="text-align:center">${t.colWeight}</th>
                <th style="text-align:right">${t.colPrice}</th>
                <th style="text-align:right">${t.colVal}</th>
              </tr>
            </thead>
            <tbody>
              ${supplier.items.map((item, idx) => {
                const price = supplier.isOrm ? item.unitPrice * 0.5 : item.unitPrice;
                return `
                <tr>
                  <td>${idx + 1}</td>
                  <td>${item.itemDescription}</td>
                  <td>${item.componentNumber}</td>
                  <td style="text-align:center">${item.quantity}</td>
                  <td style="text-align:center">${item.weight || '-'}</td>
                  <td style="text-align:right">${price.toFixed(2)} ${supplier.currency}</td>
                  <td style="text-align:right">${(item.quantity * price).toFixed(2)} ${supplier.currency}</td>
                </tr>
              `}).join('')}
            </tbody>
          </table>
          <div class="total-section">
            <div>${t.sumNet}: ${supplier.items.reduce((s, i) => s + (i.quantity * (supplier.isOrm ? i.unitPrice * 0.5 : i.unitPrice)), 0).toFixed(2)} ${supplier.currency}</div>
            ${supplier.discount > 0 ? `<div style="font-size:14px; color:#666; margin-top:5px;">${t.discount}: ${supplier.discount}%</div>` : ''}
            <div style="margin-top:10px; font-size: 22px;">${t.total}: ${total.toFixed(2)} ${supplier.currency}</div>
          </div>
          
          ${notesHtml}

          <div class="footer">${t.footer}</div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
  };


  // --- Timeline Calculations ---
  const projectStartDate = data.meta.orderDate ? new Date(data.meta.orderDate) : new Date();
  
  const timelineItems = activeSuppliers
    .filter(s => s.deliveryDate)
    .map(s => ({
        ...s,
        dateObj: s.deliveryDate === 'ASAP' ? new Date() : new Date(s.deliveryDate),
        isAsap: s.deliveryDate === 'ASAP'
    }))
    .sort((a, b) => a.dateObj.getTime() - b.dateObj.getTime());

  let minDate = projectStartDate.getTime();
  let maxDate = projectStartDate.getTime() + (30 * 24 * 60 * 60 * 1000); 
  
  if (timelineItems.length > 0) {
      const last = timelineItems[timelineItems.length - 1].dateObj.getTime();
      if (last > maxDate) maxDate = last + (7 * 24 * 60 * 60 * 1000); 
  }
  
  const totalDuration = maxDate - minDate;


  // --- LOGISTICS GROUPING LOGIC ---
  
  // 1. Identify Combined Transports
  const combinedTransports = data.transport.filter(t => t.linkedSupplierIds && t.linkedSupplierIds.length > 0);
  const combinedSupplierIds = combinedTransports.flatMap(t => t.linkedSupplierIds || []);

  // 2. Identify "Single" Suppliers (Not in Combined, Not Supplier Organized)
  const singleJHTransportSuppliers = activeSuppliers.filter(s => {
      const isCombined = combinedSupplierIds.includes(s.id);
      const tItem = data.transport.find(t => t.supplierId === s.id);
      return !isCombined && !tItem?.isSupplierOrganized;
  });

  // 3. Identify Supplier Organized (Not in Combined - though unlikely to overlap)
  const supplierTransportSuppliers = activeSuppliers.filter(s => {
      const isCombined = combinedSupplierIds.includes(s.id);
      const tItem = data.transport.find(t => t.supplierId === s.id);
      return !isCombined && tItem?.isSupplierOrganized;
  });


  const renderSupplierRow = (supplier: Supplier, isSupplierTransport: boolean, isCombinedChild: boolean = false) => {
      const tItem = data.transport.find(t => t.supplierId === supplier.id);
      const totalSupplierWeight = supplier.items.reduce((s, i) => s + (i.weight * i.quantity), 0);

      return (
        <div key={supplier.id} className={`p-6 hover:bg-zinc-50 transition-colors border-b last:border-b-0 ${isCombinedChild ? 'bg-zinc-50/50' : ''}`}>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-4">
                <div>
                    <div className="flex items-center gap-2 mb-1">
                        <h4 className="text-lg font-bold text-zinc-800">{supplier.name}</h4>
                        {supplier.isOrm && <span className="text-[10px] bg-green-600 text-white px-1.5 rounded border border-green-200">ORM</span>}
                        
                        {!isCombinedChild && (
                            <div className={`text-[10px] px-2 py-0.5 rounded-full border flex items-center gap-1 font-semibold ${isSupplierTransport ? 'bg-zinc-100 text-zinc-700 border-zinc-200' : 'bg-yellow-50 text-yellow-800 border-yellow-200'}`}>
                                {isSupplierTransport ? <UserCircle size={12}/> : <Truck size={12}/>}
                                {isSupplierTransport ? 'Transport Dostawcy' : 'Transport JH'}
                            </div>
                        )}
                    </div>
                    <div className="text-sm text-gray-500 flex flex-wrap gap-4">
                        <span>Oferta: <strong className="text-gray-700">{supplier.offerNumber || '-'}</strong></span>
                        <span className="flex items-center gap-1">
                            Data dostawy: 
                            {supplier.deliveryDate === 'ASAP' ? (
                                <span className="text-red-500 font-bold bg-red-50 px-1 rounded text-xs border border-red-100">ASAP</span>
                            ) : (
                                <strong className="text-gray-700">{supplier.deliveryDate || '-'}</strong>
                            )}
                        </span>
                    </div>
                </div>
                
                <div className="flex items-center gap-4">
                    <div className="text-right mr-4">
                        <div className="text-xs text-gray-400 uppercase">Waga</div>
                        <div className="font-mono font-bold text-zinc-700">{totalSupplierWeight.toFixed(2)} kg</div>
                    </div>
                    
                    <select
                        value={supplier.status}
                        onChange={(e) => onUpdateSupplier(supplier.id, { status: e.target.value as SupplierStatus })}
                        className={`px-3 py-1.5 rounded-full border text-sm font-bold flex items-center gap-2 outline-none cursor-pointer appearance-none ${getStatusColor(supplier.status)}`}
                    >
                        <option value={SupplierStatus.TO_ORDER}>DO ZAMÓWIENIA</option>
                        <option value={SupplierStatus.ORDERED}>ZAMÓWIONE</option>
                    </select>

                    <div className="flex items-center gap-2">
                        {/* Language Selector */}
                        <div className="relative">
                            <Globe className="absolute left-2 top-2 text-gray-400" size={14} />
                            <select
                                value={supplier.language}
                                onChange={(e) => onUpdateSupplier(supplier.id, { language: e.target.value as Language })}
                                className="pl-7 p-2 border rounded text-sm bg-white hover:border-yellow-400 cursor-pointer"
                                title="Język zamówienia (PDF)"
                            >
                                <option value={Language.PL}>PL</option>
                                <option value={Language.EN}>EN</option>
                            </select>
                        </div>

                        <button 
                            onClick={() => generateOrderPDF(supplier)}
                            className="text-gray-500 hover:text-zinc-800 border border-gray-200 hover:border-zinc-300 rounded p-2 transition-colors bg-white"
                            title="Generuj PDF Zamówienia"
                        >
                            <Printer size={18} />
                        </button>
                    </div>
                </div>
            </div>

            {/* Linked Transport Details - Only show if NOT combined child (Combined parent handles it) */}
            {!isCombinedChild && tItem && (
                <div className={`rounded p-3 border text-sm flex items-center gap-4 ${isSupplierTransport ? 'bg-zinc-50 border-zinc-200' : 'bg-yellow-50/50 border-yellow-100'}`}>
                    <div className="font-semibold text-gray-700 flex items-center gap-2">
                        <Truck size={14} className={isSupplierTransport ? 'text-zinc-500' : 'text-yellow-600'} /> 
                        Szczegóły Transportu:
                    </div>
                    {isSupplierTransport ? (
                        <span className="text-zinc-600 italic">Koszt i organizacja po stronie dostawcy.</span>
                    ) : (
                        <div className="flex gap-4">
                            <span>Ilość aut: <strong>{tItem.trucksCount}</strong></span>
                            <span className="text-gray-500">Koszt: <strong>{tItem.totalPrice.toFixed(2)} {tItem.currency}</strong></span>
                        </div>
                    )}
                </div>
            )}
        </div>
      );
  };

  const renderCombinedTransportCard = (transport: TransportItem) => {
      const linkedSuppliers = activeSuppliers.filter(s => transport.linkedSupplierIds?.includes(s.id));
      const totalCombinedWeight = linkedSuppliers.reduce((sum, s) => sum + s.items.reduce((iSum, i) => iSum + (i.weight * i.quantity), 0), 0);

      if (linkedSuppliers.length === 0) return null;

      return (
          <div key={transport.id} className="border-b-4 border-zinc-200 last:border-b-0">
               {/* Combined Header */}
               <div className="bg-blue-50 dark:bg-blue-900/10 p-4 border-b border-blue-100 dark:border-blue-900/30 flex justify-between items-center">
                   <div className="flex items-center gap-3">
                       <div className="bg-blue-500 text-white p-2 rounded shadow-sm">
                           <Combine size={20} />
                       </div>
                       <div>
                           <h4 className="font-bold text-zinc-800 dark:text-zinc-200">{transport.name}</h4>
                           <div className="text-xs text-zinc-500">
                               Transport Zbiorczy (JH) | 
                               Łączy: {linkedSuppliers.map(s => s.customTabName || s.name).join(', ')}
                           </div>
                       </div>
                   </div>
                   <div className="flex gap-6 text-sm">
                        <div className="text-right">
                           <div className="text-[10px] text-zinc-400 uppercase font-bold">Auta</div>
                           <div className="font-bold text-zinc-800">{transport.trucksCount}</div>
                        </div>
                        <div className="text-right">
                           <div className="text-[10px] text-zinc-400 uppercase font-bold">Waga Całk.</div>
                           <div className="font-mono font-bold text-blue-700">{totalCombinedWeight.toFixed(2)} kg</div>
                        </div>
                   </div>
               </div>

               {/* Child Suppliers */}
               <div className="divide-y divide-zinc-100">
                   {linkedSuppliers.map(s => renderSupplierRow(s, false, true))}
               </div>
          </div>
      );
  };

  return (
    <div className="space-y-8 animate-fadeIn">
        {/* Dashboard Header Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-white p-4 rounded-lg shadow-sm border border-zinc-200">
                <div className="flex items-center gap-2 text-zinc-500 mb-1">
                    <Package size={18} />
                    <span className="text-xs font-bold uppercase">Całkowita Waga</span>
                </div>
                <div className="text-2xl font-bold text-zinc-800">{totalWeight.toLocaleString()} kg</div>
            </div>
             <div className="bg-white p-4 rounded-lg shadow-sm border border-zinc-200">
                <div className="flex items-center gap-2 text-zinc-500 mb-1">
                    <Truck size={18} />
                    <span className="text-xs font-bold uppercase">Ilość Aut (Plan)</span>
                </div>
                <div className="text-2xl font-bold text-zinc-800">{totalTrucks}</div>
            </div>
             <div className="bg-white p-4 rounded-lg shadow-sm border border-zinc-200 md:col-span-2">
                <div className="flex items-center gap-2 text-zinc-500 mb-3">
                    <BarChart size={18} />
                    <span className="text-xs font-bold uppercase">Status Zamówień</span>
                </div>
                <div className="flex gap-2">
                    <div className="flex-1 bg-red-50 rounded p-2 text-center border border-red-100">
                        <div className="text-xs text-red-500 font-medium">Do Zamówienia</div>
                        <div className="font-bold text-red-700">{statusCounts[SupplierStatus.TO_ORDER]}</div>
                    </div>
                    <div className="flex-1 bg-green-50 rounded p-2 text-center border border-green-100">
                        <div className="text-xs text-green-500 font-medium">Zamówione</div>
                        <div className="font-bold text-green-700">{statusCounts[SupplierStatus.ORDERED]}</div>
                    </div>
                </div>
            </div>
        </div>
        
        {/* Linear Timeline View */}
        <div className="bg-white rounded-lg shadow-sm border border-zinc-200 p-6 overflow-x-auto">
            <h3 className="text-lg font-bold text-zinc-800 mb-6 flex items-center gap-2">
                <Calendar className="text-yellow-500" /> Oś Czasu (Plan Dostaw)
            </h3>
            
            <div className="relative min-w-[800px] h-32 pt-8">
                {/* Main Axis Line */}
                <div className="absolute left-0 right-0 top-1/2 h-1 bg-zinc-200 rounded"></div>
                
                {/* Start Point */}
                <div className="absolute left-0 top-1/2 -translate-y-1/2 flex flex-col items-center">
                    <div className="w-4 h-4 rounded-full bg-zinc-800 border-2 border-white shadow-sm z-10"></div>
                    <div className="mt-4 text-xs font-bold text-zinc-600 text-center w-24">
                        START<br/>{projectStartDate.toLocaleDateString()}
                    </div>
                </div>

                {/* Markers */}
                {timelineItems.map((s, idx) => {
                     const time = s.dateObj.getTime();
                     const percent = ((time - minDate) / totalDuration) * 95; // Scale to 95% to avoid edge clipping
                     const leftPos = Math.max(5, percent); // min 5% left offset
                     
                     return (
                         <div 
                            key={s.id} 
                            className="absolute top-1/2 -translate-y-1/2 flex flex-col items-center group cursor-pointer"
                            style={{ left: `${leftPos}%` }}
                         >
                             {/* Tooltip */}
                             <div className="absolute bottom-full mb-2 bg-black text-white text-[10px] py-1 px-2 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-20">
                                 {s.name} ({s.isAsap ? 'ASAP' : s.deliveryDate})
                             </div>

                             {/* Dot */}
                             <div className={`w-3 h-3 rounded-full border-2 border-white shadow-sm z-10 
                                ${s.status === SupplierStatus.ORDERED ? 'bg-green-600' : s.isAsap ? 'bg-red-500 animate-pulse' : 'bg-red-400'}`}
                             ></div>
                             
                             {/* Label */}
                             <div className="mt-4 text-[10px] font-medium text-gray-500 text-center max-w-[80px] leading-tight truncate">
                                 {s.isAsap ? (
                                    <span className="text-red-600 font-bold bg-red-50 px-1 rounded">ASAP</span>
                                 ) : (
                                    s.deliveryDate
                                 )}
                                 <br/>
                                 <span className="text-gray-800 font-bold">{s.name}</span>
                             </div>
                         </div>
                     );
                })}
            </div>
        </div>

        {/* List: Transport JH */}
        <div className="bg-white rounded-lg shadow-sm border border-zinc-200 overflow-hidden">
            <div className="bg-yellow-500 px-6 py-4 flex items-center justify-between">
                <h3 className="text-zinc-900 font-bold flex items-center gap-2">
                    <Truck className="text-zinc-800" /> Transport Organizowany przez JH
                </h3>
                <div className="flex gap-2">
                    <span className="text-xs font-semibold bg-white/20 px-2 py-1 rounded text-zinc-900 flex items-center gap-1"><Layers size={12}/> {combinedTransports.length} zbiorcze</span>
                    <span className="text-xs font-semibold bg-white/20 px-2 py-1 rounded text-zinc-900 flex items-center gap-1"><Truck size={12}/> {singleJHTransportSuppliers.length} pojedyńcze</span>
                </div>
            </div>
            
            <div className="flex flex-col">
                {combinedTransports.length === 0 && singleJHTransportSuppliers.length === 0 && (
                    <div className="p-8 text-center text-gray-400 italic">Brak dostawców w tej kategorii.</div>
                )}
                
                {/* 1. Render Combined Transports First */}
                {combinedTransports.map(t => renderCombinedTransportCard(t))}

                {/* 2. Render Remaining Single Suppliers */}
                <div className="divide-y divide-zinc-100">
                    {singleJHTransportSuppliers.map(s => renderSupplierRow(s, false))}
                </div>
            </div>
        </div>

         {/* List: Transport Supplier */}
         <div className="bg-white rounded-lg shadow-sm border border-zinc-200 overflow-hidden">
            <div className="bg-zinc-700 px-6 py-4 flex items-center justify-between">
                <h3 className="text-white font-bold flex items-center gap-2">
                    <UserCircle className="text-zinc-100" /> Transport Organizowany przez Dostawcę
                </h3>
                <span className="text-xs font-semibold bg-white/20 px-2 py-1 rounded text-white">{supplierTransportSuppliers.length} dostawców</span>
            </div>
            
            <div className="divide-y divide-zinc-100">
                {supplierTransportSuppliers.length === 0 && (
                    <div className="p-8 text-center text-gray-400 italic">Brak dostawców w tej kategorii.</div>
                )}
                {supplierTransportSuppliers.map(s => renderSupplierRow(s, true))}
            </div>
        </div>
    </div>
  );
};
